data:
  embedding_type: prostt5
  subset: tolerant
model:
  type: fnn
  params:
    hidden_layer_sizes:
    - 256
    - 64
    dropout_rate: 0.4
training:
  learning_rate: 0.001
  n_splits: 5
  max_epochs: 250
  batch_size: 256
validation:
  batch_size: 1024
