defaults:
  - dataset: strict
  - model: fnn
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null
  run:
    dir: .

embedding_type: prostt5

training:
  learning_rate: 1e-3
  n_splits: 5
  max_epochs: 1000
  batch_size: 256

validation:
  batch_size: 1024
